
import type { Metadata } from "next";
import "./globals.css";
import { Myprovider } from "./contexts/myContext";



export const metadata: Metadata = {
  title: "Serviços",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {
          <Myprovider>
            {children}
          </Myprovider>
        }
      </body>
    </html>
  );
}
